# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: myblog
  user: root
  password: 9261adoni
  encoding: utf8
  pool: 5
  timeout: 5000

# Warning: The database defined as "test" will be erased and
